name: Tests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/cpp:ubuntu24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run tests
        run: ./test-pzip.sh
